import base64
import io
import json
from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "public" / "assets"
OUTPUT = ROOT / "public" / "vendor" / "pdf-assets.js"


def encode_image(image, image_format, quality=None):
    buffer = io.BytesIO()
    options = {"optimize": True}
    if quality is not None:
        options["quality"] = quality
        options["progressive"] = True
    image.save(buffer, format=image_format, **options)
    mime = "image/jpeg" if image_format == "JPEG" else "image/png"
    return {
        "data": f"data:{mime};base64,{base64.b64encode(buffer.getvalue()).decode('ascii')}",
        "width": image.width,
        "height": image.height,
        "format": image_format,
    }


def brochure_asset(filename):
    with Image.open(ASSETS / filename) as source:
        image = source.convert("RGB")
        image.thumbnail((1600, 1600), Image.Resampling.LANCZOS)
        return encode_image(image, "JPEG", quality=92)


def main():
    assets = {}

    with Image.open(ASSETS / "shree-kali-logo.png") as source:
        assets["logo"] = encode_image(source.convert("RGBA"), "PNG")

    with Image.open(ASSETS / "approved-quotation-reference.jpg") as source:
        stamp = source.crop((750, 1308, 882, 1440)).convert("RGB")
        assets["stamp"] = encode_image(stamp, "JPEG", quality=96)

    for filename in (
        "nexon-1kg-new.jpg",
        "nexon-3kg.png",
        "nexon-5kg.png",
        "nexon-10kg.png",
        "nexon-20kg.png",
    ):
        assets[f"public/assets/{filename}"] = brochure_asset(filename)

    OUTPUT.write_text(
        "// Generated by scripts/build_pdf_assets.py.\n"
        f"window.SKM_PDF_ASSETS={json.dumps(assets, separators=(',', ':'))};\n",
        encoding="utf-8",
    )
    print(OUTPUT)


if __name__ == "__main__":
    main()
